spring:
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://observability:10000}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://links-postgres:5432/links}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery:8761/eureka/}
