services:
  auth-postgres:
    environment:
      POSTGRES_DB: authenticator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    networks:
      - backend
      - dev-access

  gateway:
    env_file:
      - ./env/dev/gateway.env
    ports:
      - "${GATEWAY_PORT:-80}:80"
    environment:
      SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_URL: http://gateway.localhost:80/
      SPRING_BOOT_ADMIN_CLIENT_INSTANCE_MANAGEMENT_URL: http://gateway.localhost:80/actuator
      SPRING_BOOT_ADMIN_CLIENT_INSTANCE_HEALTH_URL: http://gateway.localhost:80/actuator/health
    networks:
      edge:
      backend:
        aliases:
          - eureka.localhost
          - gateway.localhost

  observability:
    env_file:
      - ./env/dev/observability.env
    environment:
      SPRING_BOOT_ADMIN_UI_PUBLIC_URL: http://admin.localhost:80/

  discovery:
    env_file:
      - ./env/dev/discovery.env
    environment:
      SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_URL: http://eureka.localhost:80/
      SPRING_BOOT_ADMIN_CLIENT_INSTANCE_MANAGEMENT_URL: http://eureka.localhost:80/actuator
      SPRING_BOOT_ADMIN_CLIENT_INSTANCE_HEALTH_URL: http://eureka.localhost:80/actuator/health

  authenticator:
    env_file:
      - ./env/dev/authenticator.env
    environment:
      APP_SECURITY_JWT_SECRET: ${DEV_JWT_SECRET:-cAUIescVgFsWtSshPjjZk+RCdTzUTgBwk6UGHbgkAdp1eDjLwrZn86MAd3XQjnNWj1lyk1VL/ECBYTWMwHdPPQ==}
      APP_BOOTSTRAP_ADMIN_EMAIL: ${BOOTSTRAP_ADMIN_EMAIL:-admin@swisscom.local}
      APP_BOOTSTRAP_ADMIN_PASSWORD: ${BOOTSTRAP_ADMIN_PASSWORD:-ChangeMe-Admin-2026!}

networks:
  dev-access:
    driver: bridge
