name: swisscom

services:

  authenticator:
    build:
      context: ../services/authenticator
    networks:
      - backend
    depends_on:
      auth-postgres:
        condition: service_healthy
      discovery:
        condition: service_healthy
      observability:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:4000/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    networks: [ backend ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  # PostgreSQL - For Authentication data storage
  auth-postgres:
    image: postgres:17
    networks:
      - backend
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  # Spring Boot Admin - For application observability
  observability:
    build:
      context: ../infrastructure/observability
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://observability:10000/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  # Eureka - For service discovery
  discovery:
    build:
      context: ../infrastructure/discovery
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://discovery:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  # Spring Cloud Gateway - For routing and load balancing
  gateway:
    build:
      context: ../infrastructure/gateway
    networks:
      - edge
      - backend
    depends_on:
      discovery:
        condition: service_healthy
      observability:
        condition: service_healthy
      #authenticator:
      #    condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://gateway:80/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  edge:
    driver: bridge
  backend:
    driver: bridge
    internal: true
volumes:
  auth_postgres_volume:
